"
RwGSInstanceMigrator is a class in GS64 implementing some basic support for migrating instances. Its instances can be used as a parameter to `Rowan platform instanceMigrator:`.

This version is just a placeholder so we can easily create extensions methods to load in GS64 specific
packages.
"
Class {
	#name : 'RwGsInstanceMigrator',
	#superclass : 'Object',
	#category : 'GS64-Migration-Tools-Compatibility',
	#package : 'GS64-Migration-Tools-Compatibility'
}
