"
In GemStone/S 64 `SymbolDictionary` is an `IdentityDictionary` in which the keys are canonical
symbols and the values are SymbolAssociations.

This version is just a placeholder so we can easily create extensions methods to load in GS64 specific
packages.
"
Class {
	#name : 'SymbolDictionary',
	#superclass : 'Object',
	#category : 'GS64-Migration-Tools-Compatibility',
	#package : 'GS64-Migration-Tools-Compatibility'
}
